name:  Mejora de Documentaci贸n
description: Sugerir mejoras o correcciones en la documentaci贸n
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por ayudarnos a mejorar la documentaci贸n de La Multisig.

  - type: input
    id: page
    attributes:
      label: P谩gina Afectada
      description: 驴Qu茅 p谩gina necesita ser mejorada?
      placeholder: /docs/defi/intro
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Tipo de Mejora
      description: 驴Qu茅 tipo de mejora propones?
      options:
        - Correcci贸n de error
        - Actualizaci贸n de contenido
        - Clarificaci贸n de explicaci贸n
        - Mejora de traducci贸n
        - Otro
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Contenido Actual
      description: 驴Qu茅 dice actualmente la documentaci贸n?
      placeholder: El texto actual dice...
    validations:
      required: false

  - type: textarea
    id: suggested
    attributes:
      label: Mejora Sugerida
      description: 驴Qu茅 cambios sugieres?
      placeholder: Deber铆a decir...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Raz贸n del Cambio
      description: 驴Por qu茅 este cambio mejorar铆a la documentaci贸n?
    validations:
      required: true
